// Required due to: https://github.com/rust-lang/rust/issues/95513
#![allow(unused_crate_dependencies)]

use libcnb_test::{assert_contains, ContainerConfig};
use test_support::{
    retry, start_container, website_nextjs_integration_test, DEFAULT_RETRIES, DEFAULT_RETRY_DELAY,
};

#[test]
#[ignore = "integration test"]
fn nextjs_app() {
    website_nextjs_integration_test("./fixtures/next_app", |ctx| {
        assert_contains!(ctx.pack_stdout, "Website (Next.js)");
        assert_contains!(ctx.pack_stdout, "Static Web Server");
        start_container(
            &ctx,
            ContainerConfig::new().env(
                "PUBLIC_WEB_INTEGRATION_TEST",
                "runtime-config-via-container-env",
            ),
            |_container, socket_addr| {
                let response = retry(DEFAULT_RETRIES, DEFAULT_RETRY_DELAY, || {
                    ureq::get(&format!("http://{socket_addr}/")).call()
                })
                .unwrap();
                let response_body = response.into_string().unwrap();
                assert_contains!(response_body, "Generated by create next app");
                assert_contains!(response_body, "To get started");

                let second_response = retry(DEFAULT_RETRIES, DEFAULT_RETRY_DELAY, || {
                    ureq::get(&format!("http://{socket_addr}/nested")).call()
                })
                .unwrap();
                let second_response_body = second_response.into_string().unwrap();
                assert_contains!(response_body, "Generated by create next app");
                assert_contains!(second_response_body, "A Nested Page");

                let not_found_result = retry(DEFAULT_RETRIES, DEFAULT_RETRY_DELAY, || {
                    ureq::get(&format!("http://{socket_addr}/non-existent-path")).call()
                });
                match not_found_result {
                    Err(ureq::Error::Status(code, response)) => {
                        assert_eq!(code, 404);
                        let response_body = response.into_string().unwrap();
                        assert_contains!(response_body, "Generated by create next app");
                        assert_contains!(response_body, "This page could not be found.");
                    }
                    Ok(_) => {
                        panic!("should respond 404 Not Found, but got 200 ok");
                    }
                    Err(error) => {
                        panic!("should respond 404 Not Found, but got other error: {error:?}");
                    }
                }
            },
        );
    });
}
