api = "0.10"

[buildpack]
id = "heroku/website"
version = "0.4.0"
name = "Heroku Website"
description = "Heroku's buildpack for static websites."
keywords = ["website", "html", "javascript", "css", "static", "heroku"]

[[buildpack.licenses]]
type = "MIT"

[[order]]

[[order.group]]
id = "heroku/release-phase"
version = "1.0.0"

[[order.group]]
id = "heroku/static-web-server"
version = "1.0.0"

[[order.group]]
id = "heroku/website-public-html"
version = "1.0.0"

[[metadata.targets]]
os = "linux"
arch = "amd64"

[[metadata.targets]]
os = "linux"
arch = "arm64"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-website" }
