description = "Heroku Front-end Web buildpacks (internal preview)"

[lifecycle]
version = "0.20.1"

[build]
image = "docker.io/heroku/heroku:24-build"

[run]
[[run.images]]
image = "docker.io/heroku/heroku:24"
mirrors = ["public.ecr.aws/heroku/heroku:24"]

[[buildpacks]]
  id = "heroku/website-nodejs"
  uri = "../website-nodejs.cnb"

[[buildpacks]]
  id = "heroku/website"
  uri = "../website.cnb"

[[order]]
  [[order.group]]
    id = "heroku/website-nodejs"
    version = "1.0.2"

[[order]]
  [[order.group]]
    id = "heroku/website"
    version = "1.0.2"
