name: Release Buildpacks

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Execute the release workflow but skip any steps that publish (for testing purposes)
        type: boolean
        default: false

jobs:
  release:
    runs-on: sfdc-hk-ubuntu-latest
    steps:
      - name: Get token for GH application (Linguist)
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ vars.LINGUIST_GH_APP_ID }}
          private-key: ${{ secrets.LINGUIST_GH_PRIVATE_KEY }}
      - name: Release
        uses: heroku/languages-github-actions/.github/workflows/_buildpacks-release.yml@latest
        with:
          app_id: ${{ vars.LINGUIST_GH_APP_ID }}
          app_private_key: ${{ secrets.LINGUIST_GH_PRIVATE_KEY }}
          cnb_registry_token: ${{ secrets.CNB_REGISTRY_RELEASE_BOT_GITHUB_TOKEN }}
          docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
          docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
          dry_run: ${{ inputs.dry_run }}
