name: Publish env-as-html-data release

on:
  push:
    branches: ["main"]

jobs:
  create-release:
    runs-on: pub-hk-ubuntu-24.04-ip
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.DEV_TOOLS_RELEASE_WORKFLOW_APP_ID }}
          private-key: ${{ secrets.DEV_TOOLS_RELEASE_WORKFLOW_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }},npm-release-workflows
      - uses: actions/checkout@v7
      - name: Checkout release workflows
        uses: actions/checkout@v7
        with:
          repository: heroku/npm-release-workflows
          token: ${{ steps.app-token.outputs.token }}
          path: workflows-repo
          ref: main
      - name: Create GitHub release
        uses: ./workflows-repo/.github/actions/release-on-push-create-release-public
        with:
          package-manager: npm
          package-directory: support/env-as-html-data
          branch_name: ${{ github.ref_name }}
          token: ${{ steps.app-token.outputs.token }}
